# Generated by Django 2.1.7 on 2019-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='favorita',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
